version: '3.7'

networks:
  bitly-network:

services:
  bitly:
    build:
      context: bitly
      dockerfile: Dockerfile-debug
    depends_on:
      - redis
    networks:
      - bitly-network
    volumes:
      - ./bitly:/project
    ports:
      - "5000:8080"
      - "50505:50505"
  redis:
    build:
      context: redis
      dockerfile: Dockerfile-debug
    networks:
      - bitly-network
    ports:
      - "6379:6379"