version: '3.7'

networks:
  bitly-network:

services:
  bitly:
    build:
      context: bitly
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - bitly-network
    volumes:
      - ./bitly:/project
    ports:
      - "5000:8080"
  redis:
    build:
      context: redis
      dockerfile: Dockerfile
    networks:
      - bitly-network