FROM openjdk:8-jdk-alpine
VOLUME /project
WORKDIR /project
ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java", \
            "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=50505", \
            "-jar", \
            "target/gs-spring-boot-docker-0.1.0.jar"]